### ISSUE TITLE
Embedded version file is invalid

### ISSUE THREAD

**Issue by hakan42** [jrossignol/WaypointManager#20]
The first line does not end with a comma, making netkan softly cry :smiling_imp:

**Comment by jrossignol** [comment]
Fixed in the 2.0.3 tarball, and permanently for the next release.  Damn you KSP-AVC and not calling me out on my invalid JSON!

The bigger question is....  why doesn't it break the jenkins build when I submit my netkan changes?   I know that it attempts to extract the tarball in the release as part of that.... :smile:

**Comment by hakan42** [comment]
Because I tried  enabling avc parsing of your mod just a few hours ago :smile:
