### ISSUE TITLE
Add option to display anti-waypoint marker on the navball

### ISSUE THREAD

**Issue by old-faraon** [jrossignol/WaypointManager#37]
Since when landing a rocket  the marker is on the invisible part of the navball and a anti-waypoint marker would allow to land precisely on it.

**Comment by jrossignol** [comment]
I'll consider this one, but keep in mind that adding waypoints to the navball is a stock behaviour, so I don't have the code to do it ready (making this a bigger change than it otherwise would be).

Meanwhile, you may want to look at [Enhanced Navball](http://forum.kerbalspaceprogram.com/threads/50524), as that may have the functionality you're looking for (and if it doesn't they may be better positioned to implement it than me).

**Comment by old-faraon** [comment]
hmmm it was stock? well serves me right for not doing enough research. Sorry for troubling You then.
